### ISSUE TITLE
[FEATURE] - Support for "reserve numbers" (reservnummer)

### ISSUE THREAD

**Issue by johanfrank** [personnummer/php#29]
**Description**
In addition to regular personnummer, and coordination numbers, Swedish government and regional agencies use a number of different numbering standards. These are sometimes called "interimnummer" or "reservnummer". Is there any interest in pull requests that would add these new number formats to the library?

**Breaking changes**
This should not affect old functionality, only append new methods to parse and determine type of number (if applicable).

**Comment by johanfrank** [comment]
For example, one format is using letters in the 8th position, i.e. `000101-R220`. This is then substituted with a `1` when calculating Luhn checksum. (The date parts would still need to be a valid date.)

**Comment by Johannestegner** [comment]
Hi there! Thank you for the feature request. I will link to it in the meta repository and start a communication with the other maintainers so we can decide on if it is something we want to add to the API!

**Comment by johanfrank** [comment]
> Hi there! Thank you for the feature request. I will link to it in the meta repository and start a communication with the other maintainers so we can decide on if it is something we want to add to the API!

Great! I have a fork with this first format implemented, so if its of interest I can always create a proper pull request.

**Comment by Johannestegner** [comment]
I will take a look at your fork tomorrow and read up a bit about the case :)

**Comment by johanfrank** [comment]
The fork is located here https://github.com/pinefox/php
