### ISSUE TITLE
[BUG] - invalid security advisory package name format for `personnummer/personnummer`

### ISSUE THREAD

**Issue by Ocramius** [personnummer/php#30]
I just got a notification about an invalid package format in the exclusion rules of `roave/security-advisories`.

Specifically, this is about the published advisory:

 * https://github.com/personnummer/php/security/advisories/GHSA-2p6g-gjp8-ggg9
 * https://github.com/advisories/GHSA-2p6g-gjp8-ggg9

The reported package name for said advisory says that the package is called `personnummer`, but the name is actually `personnummer/personnummer`:

https://github.com/personnummer/php/blob/ea68e6030891c14df44f8989c458d868b335b0e5/composer.json#L2

Would you be able to edit the advisory to fit this naming? I'd then re-trigger the build of [`roave/security-advisories`](https://github.com/Roave/SecurityAdvisoriesBuilder/runs/1102314368)

**Comment by Johannestegner** [comment]
Thank you! That's my mistake, sorry.
We have updated the advisory package name, I think that the published advisory on gitlab db will take a day or so to update, so very sorry for the trouble!

I will keep this open til I see that it have been updated in the database.

**Comment by Ocramius** [comment]
@Johannestegner thanks, I do indeed see that it is lagging a bit.

I'll keep it checked, since I don't wish to spend the weekend fixing this bug xD

Thanks for the quick response!

**Comment by Johannestegner** [comment]
It seems to be updated now, so I'll close the issue. Thanks again, and sorry for the mistake (had to release 20 or so advisories at once, so yeah... hehe)!

Have a nice weekend! :)

**Comment by Ocramius** [comment]
FWIW, it got synchronised downstream @ https://github.com/Roave/SecurityAdvisories/commit/425be18066a07ae07112a0aec85bf16f9cd02ed1

Thanks for your quick help, @Johannestegner!

**Comment by Johannestegner** [comment]
Any time @Ocramius!

Btw, love the package, thank you for your service! ;)
